version: '3.9'
services:
  feedme:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
