version: '3.9'
services:
  feedme:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - POST=3000
      - DB_HOST=mongo
      - DB_PORT=27017
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
