name: Create release on tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t registry.bandcochon.fr/bandcochon/feedme .

