name: Create release on tag

on:
  workflow_dispatch:
  push:
    tags:
      - 'release-*'
jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get lastest git tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=${latest_tag}" >> $GITHUB_ENV

      - name: Build docker image
        run: docker build -t registry.bandcochon.fr/bandcochon/feedme:${{ env.LATEST_TAG }} .

      - name: Register to the register
        run: docker login --username ${{ secrets.REGISTRY_LOGIN }} --password ${{ secrets.REGISTRY_PASSWORD }} registry.bandcochon.fr

      - name: Publish image
        run: docker push

