name: Test on CI

on:
  push:
    branches: 
      - 'refs/head/*'

    paths-ignore:
      - '.github/**'
      - .gitignore
      - .dockerignore
      - '*.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '17.3.x'

      - name: Install packages
        run: npm install

      - name: Run unittests
        run: npm test
