name: Test on CI

on: [push, pull_request]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '18.3.x'

      - name: Install packages
        run: npm install

      - name: Run unittests
        run: npm test

      - name: Start the stack and run tests
        run: |
          docker-compose up -d
          npm run test-features

      - name: Stop stack
        if: always()
        run: docker-compose down